name: studiogan
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - astunparse=1.6.3=py_0
  - blas=1.0=mkl
  - bottleneck=1.3.2=py39hdd57654_1
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py39h06a4308_2
  - cffi=1.15.0=py39hd667e15_1
  - cryptography=36.0.0=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.10.0=py39h06a4308_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - future=0.18.2=py39h06a4308_1
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9d=h7f8727e_0
  - kiwisolver=1.3.1=py39h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.4.3=py39h06a4308_0
  - matplotlib-base=3.4.3=py39hbbc1b5f_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-include=2022.0.1=h06a4308_117
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=heee7806_1
  - nettle=3.7.3=hbbd107a_1
  - numexpr=2.7.3=py39h22e1b3c_1
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1m=h7f8727e_0
  - pandas=1.3.4=py39h8c16a72_0
  - pcre=8.45=h295c915_0
  - pillow=8.4.0=py39h5aabda8_0
  - pip=21.2.4=py39h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.10.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - scipy=1.7.1=py39h292c36d_2
  - seaborn=0.11.2=pyhd3eb1b0_0
  - setuptools=58.0.4=py39h06a4308_0
  - sip=4.19.13=py39h2531618_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.10.0=py39_cu113
  - torchvision=0.11.1=py39_cu113
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021e=hda174b7_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.0.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - cachetools==4.2.4
    - calmjs==3.4.2
    - calmjs-parse==1.3.0
    - calmjs-types==1.0.1
    - charset-normalizer==2.0.7
    - click==8.0.4
    - clip==1.0
    - cmake==3.22.3
    - contextlib2==21.6.0
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - executing==0.8.3
    - ftfy==6.1.1
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grad-cam==1.3.7
    - grpcio==1.41.1
    - h5py==3.5.0
    - ipykernel==6.9.2
    - ipython==8.1.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-client==7.1.2
    - jupyter-console==6.4.3
    - jupyter-core==4.9.2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.1.0
    - kornia==0.6.3
    - lab==7.0
    - llvmlite==0.39.1
    - lmdb==1.2.1
    - markdown==3.3.4
    - markupsafe==2.1.0
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - ml-collections==0.1.0
    - nbclient==0.5.13
    - nbconvert==6.4.4
    - nbformat==5.2.0
    - nest-asyncio==1.5.4
    - ninja==1.10.2.3
    - notebook==6.4.10
    - numba==0.56.4
    - oauthlib==3.1.1
    - opencv-python==4.5.5.62
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - ply==3.11
    - prettytable==2.4.0
    - prometheus-client==0.13.1
    - promise==2.3
    - prompt-toolkit==3.0.28
    - protobuf==3.19.1
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.11.2
    - pynndescent==0.5.8
    - pyrsistent==0.18.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - qtconsole==5.2.2
    - qtpy==2.0.1
    - regex==2022.10.31
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-learn==1.0.1
    - send2trash==1.8.0
    - sentry-sdk==1.5.7
    - setproctitle==1.2.2
    - shortuuid==1.0.8
    - simplejson==3.17.6
    - sklearn==0.0
    - smmap==5.0.0
    - soupsieve==2.3.1
    - stack-data==0.2.0
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - termcolor==1.1.0
    - terminado==0.13.3
    - testpath==0.6.0
    - threadpoolctl==3.0.0
    - traitlets==5.1.1
    - ttach==0.0.3
    - txt2tags==3.7
    - umap-learn==0.5.3
    - urllib3==1.26.7
    - wandb==0.12.11
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.2
    - widgetsnbextension==3.6.0
    - yaspin==2.1.0
